sudo: false
dist: trusty

compiler: gcc

before_install: source scripts/setup_environment.sh
    
install: scripts/firmware.sh --command=unit-test-host --target=test

git:
    depth: 3

env:
- BLUENET_WORKSPACE_DIR=$HOME/workspace BLUENET_DIR=$TRAVIS_BUILD_DIR
  
# blocklist
branches:
    except:
    - gh-pages
